name: generate-plantuml-image
on: 
  push: 
    path: 'README.md'
jobs:
  generate-plantuml-image:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: ts-graphviz/setup-graphviz@v1
      - run: awk \
          '
          BEGIN {count = 0;}
          /[ ]*```plantuml[ ]*$/ { 
            inuml = 1; 
            count = count + 1; 
            fname = "tmp" count ".puml"; 
            imgname = "fig" count ".png";
          }
          /[ ]*```[ ]*$/ { 
            if (inuml > 0) inuml = -1;
          }
          {
            if (inuml > 1) print >> fname; 
            if (inuml == 1) print "![fig](" imgname ")";
            if (inuml == 0) print;
            if (inuml == 1) inuml = 2;
            if (inuml == -1) inuml = 0;
          }
         ' < README.md > .github/README.md
      - run: for fn in `ls tmp*.puml`;do
            imgname=`echo $fn | sed -e 's/^tmp/fig/' -e 's/puml$/png/'`;
            echo "$fn ==> $imgname" ;
            LANG=ja_JP.UTF-8 npx node-plantuml generate $fn -p -o .github/$imgname;
          done
      - run: rm tmp*.puml
      - uses: EndBug/add-and-commit@v9
        with: 
          add: '.github'
          message: '[Auto] generated uml diagrams.'
